### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by elihurubin** [coreytegeler/nhba#11]
Captions still not showing up under photo.  I'm trying to "Update" between adding new photos -- not batch uploading, in other words, but not sure that makes a difference.

**Comment by coreytegeler** [comment]
Could you give as example of a building with captioned images that are not working?

**Comment by elihurubin** [comment]
None that I can see work.  Is http://34.193.46.57/    the best place for me to work on the site right now?

**Comment by coreytegeler** [comment]
yeah, that's where it was moved.

can you give an example? the one's I am testing work fine

**Comment by elihurubin** [comment]
400 East Street and 293 East.  Was just working on both of them.

**Comment by coreytegeler** [comment]
293 East had been created twice, which I just noticed a few minutes ago and
fixed. I was also able to manually fix 400 East, but I think the issue I
need to work on is that the captions may not be saving when you add an
image, only when you update a previously uploaded one

**Comment by elihurubin** [comment]
I think that's right.  It works by updating previously uploaded image.  I just added two more on 293 East Street, and batch uploading a number of added captions works, so that's good.

**Comment by coreytegeler** [comment]
Thought I had fixed this pre-Thanksgiving but was just reminded that I
never made it all the way through the issue. It'll be done tonight.

**Comment by coreytegeler** [comment]
should be better now, but please let me know if it still acting unfavorably
