### ISSUE TITLE
Trouble Adding Photos . . .

### ISSUE THREAD

**Issue by elihurubin** [coreytegeler/nhba#15]
. . . to existing entries, like 233 Edwards.

**Comment by coreytegeler** [comment]
just reuploaded them after doing a manual fix

seems to be something about previously uploaded images before doing a major fix to how they get saved.

let me know if this happens to any newly created entry

**Comment by elihurubin** [comment]
Went to fix 978 Chapel Street and new picture not appearing.  The rest of my edits are fine.

**Comment by coreytegeler** [comment]
do they show up after you update the entry?

**Comment by coreytegeler** [comment]
I found the same issue as 233 Edwards. If you look close you could see an extra space to the left of the first image in the building entry form, this is from an issue I need to fix manually, unless you see it after creating a new building, then I would need to further debug
